CREATE TABLE [dbo].[PRODUCTO] (
    [id_producto]                INT             IDENTITY (1, 1) NOT NULL,
    [id_empresa]                 INT             NOT NULL,
    [codigo]                     VARCHAR (50)    NOT NULL,
    [nombre]                     VARCHAR (150)   NOT NULL,
    [descripcion]                VARCHAR (300)   NULL,
    [tipo_producto]              VARCHAR (50)    NOT NULL,
    [unidad_medida]              VARCHAR (50)    NULL,
    [costo_promedio]             DECIMAL (18, 4) NULL,
    [precio_venta]               DECIMAL (18, 2) NOT NULL,
    [inventariable]              BIT             DEFAULT ((1)) NOT NULL,
    [id_estado]                  INT             NOT NULL,
    [fecha_creacion]             DATETIME2 (7)   DEFAULT (sysdatetime()) NOT NULL,
    [fecha_modificacion]         DATETIME2 (7)   NULL,
    [politica_facturacion]       VARCHAR (50)    NOT NULL,
    [porcentaje_impuesto_venta]  DECIMAL (8, 4)  NOT NULL,
    [porcentaje_impuesto_compra] DECIMAL (8, 4)  NOT NULL,
    [peso]                       DECIMAL (18, 4) NULL,
    [volumen]                    DECIMAL (18, 4) NULL,
    [tiempo_entrega]             INT             NOT NULL,
    [id_cuenta_ingreso]          INT             NOT NULL,
    [id_cuenta_gasto]            INT             NOT NULL,
    CONSTRAINT [PK_PRODUCTO] PRIMARY KEY CLUSTERED ([id_producto] ASC),
    CONSTRAINT [CK_PRODUCTO_COSTO_PROMEDIO] CHECK ([costo_promedio] IS NULL OR [costo_promedio]>=(0)),
    CONSTRAINT [CK_PRODUCTO_IMPUESTO_COMPRA] CHECK ([porcentaje_impuesto_compra]>=(0)),
    CONSTRAINT [CK_PRODUCTO_IMPUESTO_VENTA] CHECK ([porcentaje_impuesto_venta]>=(0)),
    CONSTRAINT [CK_PRODUCTO_PESO] CHECK ([peso] IS NULL OR [peso]>=(0)),
    CONSTRAINT [CK_PRODUCTO_POLITICA] CHECK ([politica_facturacion]='cantidad entregada' OR [politica_facturacion]='cantidad ordenada'),
    CONSTRAINT [CK_PRODUCTO_PRECIO_VENTA] CHECK ([precio_venta]>=(0)),
    CONSTRAINT [CK_PRODUCTO_TIEMPO_ENTREGA] CHECK ([tiempo_entrega]>=(0)),
    CONSTRAINT [CK_PRODUCTO_TIPO] CHECK ([tipo_producto]='combo' OR [tipo_producto]='servicios' OR [tipo_producto]='bienes'),
    CONSTRAINT [CK_PRODUCTO_VOLUMEN] CHECK ([volumen] IS NULL OR [volumen]>=(0)),
    CONSTRAINT [FK_PRODUCTO_CUENTA_GASTO] FOREIGN KEY ([id_cuenta_gasto]) REFERENCES [dbo].[CUENTA_CONTABLE] ([id_cuenta_contable]),
    CONSTRAINT [FK_PRODUCTO_CUENTA_INGRESO] FOREIGN KEY ([id_cuenta_ingreso]) REFERENCES [dbo].[CUENTA_CONTABLE] ([id_cuenta_contable]),
    CONSTRAINT [FK_PRODUCTO_EMPRESA] FOREIGN KEY ([id_empresa]) REFERENCES [dbo].[EMPRESA] ([id_empresa]),
    CONSTRAINT [FK_PRODUCTO_ESTADO] FOREIGN KEY ([id_estado]) REFERENCES [dbo].[ESTADO] ([id_estado])
);

